apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-reviews
  namespace: argocd
spec:
  destination:
    namespace: stg
    server: https://kubernetes.default.svc
  project: stg-bookinfo
  source:
    kustomize:
      namePrefix: stg-
    path: deploy/overlays/stg
    repoURL: https://gitlab.com/cloudnative_impress/bookinfo-manifests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
