apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
namespace: prod

images:
- digest: sha256:85be0ca4ed1fd5204720cc15dafcb938e97d53010210534013f0f55cff389645
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: registry.gitlab.com/cloudnative_impress/bookinfo/reviews

resources:
- ../../base

patchesStrategicMerge:
- deployments.yaml
