apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
namespace: prod

images:
- digest: a82d565dd12b7156b8e988b9d2cc8ed982d78a59
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: registry.gitlab.com/cloudnative_impress/bookinfo

resources:
- ../../base

patchesStrategicMerge:
- deployments.yaml
