---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: security
spec:
  description: >-
    This Task scans Comprehensive Vulnerability using Trivy for Containers
    and other Artifacts, Suitable in CI.
  params:
  - name: IMAGE
    description: Reference of the image Trivy will scan.
  - name: IMAGE_DIGEST
    description: Reference of the image digest Trivy will scan.
  - name: TRIVY_IMAGE
    description: The location of the Trivy scan image.
    default: aquasec/trivy:0.15.0
  workspaces:
  - name: cache
  - name: report
    readOnly: false
  stepTemplate:
    env:
    - name: TRIVY_USERNAME
      valueFrom:
        secretKeyRef:
          name: gitlab-token
          key: username
          optional: true
    - name: TRIVY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: gitlab-token
          key: password
          optional: true
  steps:
  - name: build-report
    image: $(params.TRIVY_IMAGE)
    script: |
      SCAN_CONTAINER_IMAGE=$(params.IMAGE)@sha256:$(params.IMAGE_DIGEST)
      trivy --cache-dir=$(workspaces.cache.path)/trivy \
        image --exit-code=0 --no-progress --severity=HIGH \
        -o=./container-scanning-report.json ${SCAN_CONTAINER_IMAGE}
  - name: get-report
    image: busybox:stable
    script: |
      mv -v container-scanning-report.json $(workspaces.report.path)/$(context.taskRun.name)-scanning-report.json
      cat $(workspaces.report.path)/$(context.taskRun.name)-scanning-report.json
  - name: severe-vulnerabilities
    image: $(params.TRIVY_IMAGE)
    script: |
      SCAN_CONTAINER_IMAGE=$(params.IMAGE)@sha256:$(params.IMAGE_DIGEST)
      trivy --cache-dir=$(workspaces.cache.path)/trivy \
        image --exit-code=1 --no-progress --severity=CRITICAL \
        ${SCAN_CONTAINER_IMAGE}
