apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec: 
  replicas: 3
  template:
    spec:
      serviceAccountName: bookinfo-reviews
