apiVersion: batch/v1
kind: Job
metadata:
  generateName: service-check-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command:
          - "curl"
          - "http://reviews/"
      restartPolicy: Never
  backoffLimit: 2
