apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: staging
  app.kubernetes.io/managed-by: kustomize
namespace: stg

images:
- digest: sha256:e9655fddd37f87368b8afde9f20bdcfcce8043327610d596db5bca6eaddf2875
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: registry.gitlab.com/cloudnative_impress/bookinfo/reviews

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- serviceaccount.yaml
