apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: staging
  app.kubernetes.io/managed-by: kustomize
namespace: stg

images:
- digest: sha256:9afb3b7f6e2507661a814ddf41020ccbe2654c0963e5c1398a453a2793073cc3
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: registry.gitlab.com/cloudnative_impress/bookinfo/reviews

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- serviceaccount.yaml
