apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-reviews
spec:
  workspaces:
  - name: bookinfo
    description: Git Repo for BookInfo Apps
  - name: bookinfo-manifests
    description: Git Repo for BookInfo Manifests
  params:
  - name: target-app
    description: Target application in BookInfo Apps
  - name: bookinfo-url
    description: Git Repo URL for BookInfo Apps
  - name: bookinfo-revision  
    description: Git Repo Revision for BookInfo Apps
  - name: bookinfo-manifests-url
    description: Git Repo URL for BookInfo Manifests
  - name: bookinfo-manifests-revision  
    description: Git Repo Revision for BookInfo Manifests
  tasks:
  - name: git-clone-bookinfo
    taskRef:
      name: git-clone
    params:
    - name: url
      value: $(params.bookinfo-url)
    - name: revision
      value: $(params.bookinfo-revision)
    workspaces:
    - name: output
      workspace: bookinfo
      
  - name: git-clone-bookinfo-manifests
    taskRef:
      name: git-clone
    params:
    - name: url
      value: $(params.bookinfo-manifests-url)
    - name: revision
      value: $(params.bookinfo-manifests-revision)
    workspaces:
    - name: output
      workspace: bookinfo-manifests

  - name: gradle-test
    taskRef:
      name: gradle-test
    runAfter:
    - git-clone-bookinfo
    workspaces:
    - name: output
      workspace: bookinfo
    params:
    - name: contextDir
      value: $(params.target-app)/reviews-application

  - name: conftest
    taskRef:
      name: conftest
    runAfter:
    - git-clone-bookinfo-manifests
    workspaces:
    - name: source
      workspace: bookinfo-manifests
    params:
    - name: files
      value: $(workspaces.source.path)/deploy/bases/bookinfo-$(params.target-app).yaml
    - name: policy
      value: $(workspaces.source.path)/deploy/policy
    - name: args
      value: ["--trace"]

  - name: build-container
    taskRef:
      name: kaniko
    runAfter:
    - gradle-test
    - conftest
    workspaces:
    - name: source
      workspace: bookinfo
    params:
    - name: IMAGE
      value: registry.gitlab.com/cloudnative_impress/bookinfo/$(params.target-app):$(context.pipelineRun.name)
    - name: CONTEXT
      value: $(params.target-app)/reviews-wlpcfg
    - name: BUILDER_IMAGE
      ##  description: kaniko v1.3.0
      value: gcr.io/kaniko-project/executor@sha256:b9eec410fa32cd77cdb7685c70f86a96debb8b087e77e63d7fe37eaadb178709

