apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: curl-sidecar
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: search
spec:
  description: >-
    This task performs curl operation to transfer data from internet.

  params:
  - name: url
    description: URL to curl'ed
    type: string
  - name: options
    description: options of url
    type: array
    default: []
  - name: curl-image
    description: option of curl image
    type: string
    default: "docker.io/curlimages/curl:7.72.0@sha256:3c3ff0c379abb1150bb586c7d55848ed4dcde4a6486b6f37d6815aed569332fe" #tag: 7.72.0
  steps:
  - name: sidecar-waiting
    image: ubuntu:21.04
    script: |
      #!/usr/bin/env bash
      echo "Wait for running sidecar in 10 seconds!"
      sleep 10
  - name: curl
    image: "$(params.curl-image)"
    command: [curl]
    args: ["$(params.options[*])", "$(params.url)"]
  sidecars:
  - name: reviews
    image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
    imagePullPolicy: IfNotPresent
    env:
    - name: LOG_DIR
      value: "/tmp/logs"
    ports:
    - containerPort: 9080
    volumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: wlp-output
      mountPath: /opt/ibm/wlp/output
  volumes:
  - name: wlp-output
    emptyDir: {}
  - name: tmp
    emptyDir: {} 
