apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source-lister
spec:
  workspaces:
    - name: output
  params:
    - name: contextDir
      description: "The context directory within the repository for sources"
      default: reviews
  steps:
    - name: ls-build-sources
      image: busybox:stable
      command: ["ls"]
      args: ["-ltr", "/workspace/output/$(inputs.params.contextDir)"]
