apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: workspaces-sample
spec:
  workspaces:
    - name: pvc-workspace1
    - name: pvc-workspace2
      readOnly: true
    - name: emptydir-workspace
    - name: cm-workspace
  steps:
    - name: ls-workspaces
      image: busybox:stable
      command: ["ls"]
      args: ["-ltrR", "/workspace"]
    - name: write-to-emptydir
      image: busybox:stable
      script: echo "Sample Workspaces - VolumeSource emptyDir" > $(workspaces.emptydir-workspace.path)/message
    - name: read-emptydir
      image: busybox:stable
      command: ["cat"]
      args: ["$(workspaces.emptydir-workspace.path)/message"]
    - name: show-configmap
      image: busybox:stable
      command: ["cat"]
      args: ["/workspace/cm-workspace/workspace-message.txt"]
