apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: buildah-build-reviews-run-
spec:
  serviceAccountName: tekton-admin
  taskRef:
    name: buildah
  podTemplate:
    securityContext:
      runAsNonRoot: true
  params:
    - name: IMAGE
      value: registry.gitlab.com/___GIT_USERNAME___/bookinfo/reviews:$(context.taskRun.uid)
    - name: CONTEXT
      value: ./reviews-wlpcfg
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: bookinfo
      subPath: reviews
