apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: conftest-reviews-run-
spec:
  taskRef:
    name: conftest
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: bookinfo-manifests
  params:
  - name: files
    value: $(workspaces.source.path)/deploy/base/bookinfo-reviews.yaml
  - name: policy
    value: $(workspaces.source.path)/deploy/policy
  - name: args
    value: ["--trace"]
