apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: conftest-manifests-run-
spec:
  taskRef:
    name: conftest
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: bookinfo-manifests
  params:
  - name: files
    value: deploy/bases/bookinfo-reviews.yaml
  - name: policy
    value: deploy/policy
