apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: gradle-build-reviews-run-
spec:
  taskRef:
    name: gradle
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: bookinfo
  params:
    - name: GRADLEOPTS
      value: ["clean", "build"]
    - name: CONTEXTDIR
      value: reviews
