apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kubectl-deploy-reviews-run-
spec:
  taskRef:
    name: kubectl-bookinfo
  workspaces:
    - name: manifest-dir
      persistentVolumeClaim:
        claimName: bookinfo-manifests
    - name: kubeconfig-dir
      secret:
        secretName: tekton-admin-kubeconfig
  params:
    - name: TARGET_APP
      value: reviews
    - name: IMAGE
      value: registry.gitlab.com/___GIT_USERNAME___/bookinfo/reviews
    - name: IMAGE_DIGEST
      value: ___IMAGE_DIGEST___
