apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kubectl-deploy-reviews-run-
spec:
  taskRef:
    name: kubectl-bookinfo
  workspaces:
    - name: manifest-dir
      persistentVolumeClaim:
        claimName: bookinfo-manifests
    - name: kubeconfig-dir
      secret:
        secretName: tekton-admin-kubeconfig
  params:
    - name: target_app
      value: reviews
    - name: imageurl
      value: docker.io/istio/examples-bookinfo-reviews-v2
    - name: imagedigest
      value: 82497d66ab8cac1ad9506218e4ccc708ec1db59450c6c4c8d645d1b161611a5d
