apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: curl-response-run
spec:
  params:
    - name: url
      value: "www.google.com"
    - name: options
      value: ["-I","--no-progress-meter"]
  taskRef:
    name: curl
