apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: gradle-test-run-
spec:
  taskRef:
    name: gradle-test
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: bookinfo
  params:
    - name: contextDir
      value: reviews/reviews-application
