apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: gradle-build-run-
spec:
  taskRef:
    name: gradle-build
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: tekton-pvc
  params:
    - name: contextDir
      value: reviews/reviews-application
