apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: gradle-build-run-
spec:
  taskRef:
    name: gradle-build
  resources:
    inputs:
      - name: source
        resourceRef:
          name: bookinfo-source
  params:
    - name: contextDir
      value: reviews/reviews-application
