apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: show-workspaces-run-
spec:
  taskRef:
    name: show-workspaces
  workspaces:
    - name: workspace-pvc1
      volumeClaimTemplate:
        spec:
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
    - name: workspace-pvc2
      persistentVolumeClaim:
        claimName: bookinfo
      subPath: reviews
    - name: workspace-emptyDir
      emptyDir: {}
    - name: workspace-configmap
      configMap:
        name: workspaces-configmap
        items:
          - key: message
            path: workspace-message.txt
