apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-cm
data:
  message: Workspaces Sample TaskRun
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: workspaces-sample-run-
spec:
  taskRef:
    name: workspaces-sample
  workspaces:
    - name: pvc-workspace1
      volumeClaimTemplate:
        spec:
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
    - name: pvc-workspace2
      persistentVolumeClaim:
        claimName: tekton-pvc
      subPath: sample
    - name: emptydir-workspace
      emptyDir: {}
      subPath: sample
    - name: cm-workspace
      configMap:
        name: tekton-cm
        items:
          - key: message
            path: workspace-message.txt
