apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-reviews-run-
spec:
  serviceAccountName: tekton-admin
  params:
  - name: target-app
    value: reviews
  - name: imageurl
    value: registry.gitlab.com/___GITLAB_USER___/bookinfo
  - name: bookinfo-url
    value: https://gitlab.com/___GITLAB_USER___/bookinfo.git
  - name: bookinfo-revision
    value: main
  - name: bookinfo-manifests-url
    value: https://gitlab.com/___GITLAB_USER___/bookinfo-manifests.git
  - name: bookinfo-manifests-revision
    value: main
  workspaces:
  - name: bookinfo
    persistentVolumeClaim:
      claimName: bookinfo
  - name: bookinfo-manifests
    persistentVolumeClaim:
      claimName: bookinfo-manifests
  - name: vul-cache
    emptyDir: {}
  pipelineRef:
    name: build-deploy-reviews
